### ISSUE TITLE
Error in diagram and suggested changes to instruction wording.

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/physical-computing#25]
URL: /en/projects/physical-computing/10

You confuse yourself with the capacitor as to which is the positive lead. In the giant picture of the capacitor, the longer lead is shown connected to the black side (which is wrong, the black side is negative) and in the breadboard diagram you say to connect the longer lead to the LDR but you show the blue side of the capacitor connected to the LDR. Personally, I wish you would not just advise on LED and capacitor connections based on the longer wire because people might have used parts that have evenly cut wires. Tell people to identify the positive side of the components.

**Comment by pablisch** [comment]
Capacitors come in different colours and it is quite normal to have the black side as positive. The large capacitor image looks correct, however, this is contradicted by the breadboard diagrams that show the polarity reversed and likely wrong. I have added reference to polarity where the capacitor is introduced, mentioned the positive polarity along with leg length in the breadboard steps and edited the breadboard images to match the capacitor image.
